In [13]:
import matplotlib.pyplot as plt
import pickle

In [49]:
with open("params", 'r') as f:
    data = pickle.load(f)

In [52]:
temp = data["HVAC_Zone_Northzone"]
for i in temp:
    print(i)
    print("/n")

[ 0.03944697 -0.1325248   0.00108189  0.02275017  0.00066806  0.00089721
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00197194  0.02230515  0.00066806  0.00129773
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00274564  0.0219183   0.00066806  0.0016459
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.0034182   0.02158202  0.00066806  0.00194855
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00400284  0.0212897   0.00066806  0.00221163
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00451105  0.02103559  0.00066806  0.00244033
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00495282  0.02081471  0.00066806  0.00263913
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00533684  0.0206227   0.00066806  0.00281194
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00567067  0.02045578  0.00066806  0.00296216
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.00596085  0.02031069  0.00066806  0.00309274
 -0.00020095]
/n
[ 0.03944697 -0.1325248   0.0062131   0.02018457  0.00066806  0.00320625
 -0.00020095]
/n
[ 0.0394469

In [16]:
import numpy as np


In [17]:
a = np.array([[1,2], [4,5]])
b = np.array([4,10])
a * b

array([[ 4, 20],
       [16, 50]])

In [20]:
np.array(a)

array([[1, 2],
       [4, 5]])

In [26]:
a[0]

array([1, 2])

In [23]:
t = np.array(np.array(a))

In [28]:
k = [[1,2], [4,5]]

In [30]:
a = np.array([[1], [2]])
b = np.array([1, 2])
a.reshape((a.shape[0])) - b

array([0, 0])

In [53]:
a = [1]

In [54]:
a[-50:]

[1]

In [91]:
def myround(x, base=0.05):
    return base * round(float(x)/base)
s = 0.17
t = 0.15 
s1 = 0.54
t = 0.55
myround(s, base=0.05)

0.15000000000000002

In [84]:
round(0.17/0.05)

3.0

In [88]:
3 * 0.05

0.15000000000000002